### ISSUE TITLE
Can't recover from sleep.

### ISSUE THREAD

**Issue by peekpt** [Ben216k/Patched-Sur#10]
**Describe the bug**
Computer doesn't recover from sleep

**To Reproduce**
1. apple menu sleep
2. wait 1 minute
3. try to wake up moving mouse and keyboard
4. Black screen

**Expected behavior**
Screen turns with login screen

**Screenshots**

Patched Sur is constantly popping this popup!
![macOS error](https://user-images.githubusercontent.com/222385/139578524-dd1a4b4d-5ce2-41e6-b18e-881d00ea7d30.png)

Patched Sur error on Installation
 
![Installation error](https://user-images.githubusercontent.com/222385/139578585-9f4a8595-ad7a-41c9-840c-478610fb50d1.jpg)

**Desktop (please complete the following information):**

- Upgrading to: [e.g. Big Sur v11.6.1]
 - Mac Model: [iMac 2011 modded Nvidia (metal) K610 GPU]
 - Version [12,2]

**Additional context**
It was working fine 1 month ago when updated with Patched Sur 0.xx version
(I didn't catch 1.0.0 went straight to 1.0.1)

**Comment by Ben216k** [comment]
Since I don't support pre-2012 Macs I'm the first place, I don't really consider this an issue.

Your sleep problem is the lack of iGPU acceleration, so it doesn't matter what dGPU you have, that'll happen.

The NVRAM popup literally tells you how to get rid of it.

The last error is another "I don't support pre-2011 Macs" error, but if you absolutely want to use Patched Sur, just go into Patch Kexts in the desktop app then Advanced Configuration then disable everything but WiFi.

**Comment by peekpt** [comment]
I understand, since you aren't supporting iMac 2012 even with modded metal GPU, I decided to try OCLP and so far everything works, sleep, brightness, wifi, usb... Thanks for your work anyway, I used for months until this issue arises.
