### ISSUE TITLE
The file “Release.json” couldn’t be opened.

### ISSUE THREAD

**Issue by JQOz** [Ben216k/Patched-Sur#14]
When I try to update patched sur I get this error message "The file “Release.json” couldn’t be opened."

![Bildschirmfoto 2021-11-02 um 16 31 16](https://user-images.githubusercontent.com/19261428/139878790-e11ebcc5-78bd-4f8d-b7da-1db9de90d6db.png)

**Comment by Ben216k** [comment]
Just use the post install DMG from Github and replace it.

That several month old version of the app has no idea that the url changed from ...BenSova... to ...Ben216k...

Also, you should really turn on update notifications, v0.2.0, v0.2.1, v1.0.0 and v1.0.1 came out since then and probably several macOS versions too.
