### ISSUE TITLE
WiFi networks are not found

### ISSUE THREAD

**Issue by phanxen** [Ben216k/Patched-Sur#44]
**Describe the bug**
First of all, a huge thanks to the whole team.

I was able to install BigSur using Patched-Sur. In the first boot after the installation WiFi was not working (as expected).

I applied kexts patches and rebooted. WiFi seemed to be fine, given I was able to turn-on/off WiFi and the WiFi icon had that animation in which the curved bars "move".

However, no WiFi network was shown. The machine seemed to be looking for networks, but any a single one was shown. I have 2 networks at home, and a few more around us (neighbors). I also tried using my mobile as hotspot, but now luck.

**To Reproduce**
1. Go to 'System Preferences > Network'
2. Click on 'Wi-Fi'
3. Wait while the system looks for a WiFi network

**Expected behavior**
WiFi networks inside the range of the laptop should be shown.

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
- Upgrading to: Big Sur v11.6.3
 - Mac Model: 13" 2012 MacBook Pro
 - Version v1.0.1 (122)

**Comment by baselbj** [comment]
I am using IMac 2011 but I can't see any network , not WIFI or Ethernet

**Comment by Ben216k** [comment]
Should have commented on this earlier, but something for both of you:

@baselbj: I don't support any pre-2012 Macs anymore, honestly I should have just added a blacklist for that model since it's the only one that people seem to get past the metal check.

@phanxen: If you're still interested, you should try repatching with v1.1.0, it included a new WiFi patch that should work much better than the original.

**Comment by phanxen** [comment]
Confirmed that the new kexts patches solved my issue. Right now I'm writing this post using my 13" 2012 MacBook Pro, running BigSur.
