### ISSUE TITLE
On my Macbook Pro mid 2012 first it doesn't recognise my mac and then crashes after I press installatiob

### ISSUE THREAD

**Issue by solitary8** [Ben216k/Patched-Sur#72]
On my Macbook Pro mid 2012

[Older iOS Safari Window with Image]

 first it doesn't recognise my mac and then crashes after I press installation.

I'm upgrading from macOs Catalina 10.15.7
[error-message.odt](https://github.com/user-attachments/files/17240150/error-message.odt)

**Comment by Ben216k** [comment]
I do not know what the screenshot you provided was for (I removed it, since it didn't seem immediately relevant and was a screenshot from an iOS Safari and contained a face) or what you mean it crashes "after I press installation". Could you run the app through terminal and send those logs? Crash reports don't give me anything other than your specs.

**Comment by solitary8** [comment]
Hi I'm sorry about the photo I miss  clicked thank you for removing it, after pressing the installation after I slept the version of the app it crashes,no need now since I managed to do it with another app but thank you for the time you gave me by responding to my issue
